name = "knowledge-vault"
compatibility_date = "2026-05-04"
pages_build_output_dir = "./dist"

[vars]
# Replace this with your actual production API URL
VITE_API_BASE_URL = "https://knowledge-vault-api.isher.dev/api"
VITE_API_WITH_CREDENTIALS = "false"
VITE_MAX_UPLOAD_MB = "15"